CREATE TABLE TRANSACTION(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CATEGORYID BIGINT NOT NULL,
  AMOUNT BIGINT NOT NULL,
  DATE BIGINT NOT NULL
);

CREATE TABLE CATEGORY(
  ID BIGINT PRIMARY KEY,
  NAME VARCHAR(64) NOT NULL
);